version: '3.8'

services:
  db:
    image: postgres:15
    container_name: repsy-db
    environment:
      POSTGRES_DB: repsy
      POSTGRES_USER: repsyuser
      POSTGRES_PASSWORD: repsysecret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: repsy-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/repsy
      SPRING_DATASOURCE_USERNAME: repsyuser
      SPRING_DATASOURCE_PASSWORD: repsysecret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      STORAGE_STRATEGY: file-system
    volumes:
      - ./storage:/app/storage

volumes:
  pgdata:
